#!/bin/bash
#
# Small installer script for Debian Buster. Meant to install 
# a few things so I don't have to remember all configurations
# for the system this project runs on.
#######################################
# Pre-Running-Script:
#   Make sure apt is not configured 
#   to see installer iso as a deb repo.
# Post-Running-Script:
#   Invalidate root account, use 
#   'sudo passwd -l root'.
#######################################
PROGRAM_NAME="$(basename "$0")"

# check to see if I am root
ROOT_ID=0
if [ "$(id -u)" != "$ROOT_ID" ]; then
    echo "${PROGRAM_NAME}: must be root to run script!"
fi

# running as root, install several pkgs and assign reap2sow1 to sudo group
apt-get install sudo openjdk-11-jdk jq gpg git zip wget --assume-yes
usermod --append --groups sudo reap2sow1

# install virtualbox
VBOX_DEB_PKG_URL="https://download.virtualbox.org/virtualbox/6.0.24/virtualbox-6.0_6.0.24-139119~Debian~buster_amd64.deb"
VBOX_DEB_PKGNAME="$(basename $VBOX_DEB_PKG_URL)"
wget --quiet --output-document "$VBOX_DEB_PKGNAME" "$VBOX_DEB_PKG_URL"
apt-get install "./${VBOX_DEB_PKGNAME}"

# install jenkins from stable release
wget --quiet --output-document - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
echo "deb https://pkg.jenkins.io/debian-stable binary/" > "/etc/apt/sources.list.d/jenkins.list"
apt-get update
apt-get install jenkins --assume-yes

# starts jenkins
systemctl start jenkins

# install few aliases
cat << _EOF_ > /home/reap2sow1/.bash_aliases
    alias egrep='egrep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias grep='grep --color=auto'
    alias l='ls -CF'
    alias la='ls -A'
    alias ll='ls -alF'
    alias ls='ls --color=auto'
_EOF_
