#!/bin/bash
#
# Small script to prepare seed job to create the 
# packerbuilds job on a jenkins instance.
set -e
PROGRAM_NAME="$(basename "$0")"
# NOTE: this is the system user that jenkins runs under,
# at least in terms of the filesystem and respective files
JOBCONFS_DIR_NAME="jobconfs"
JENKINS_SYSTEM_USERNAME="jenkins"
JENKINS_HOME="/var/lib/jenkins/"
SEED_WORKSPACE="${JENKINS_HOME}/workspace/seed/"

# check to see if I am root
ROOT_ID=0
if [ "$(id -u)" != "$ROOT_ID" ]; then
    echo "${PROGRAM_NAME}: must be root to run script!"
    exit 1
fi

if [ -z "$(which rsync)" ]; then
    echo "${PROGRAM_NAME}: rsync cannot be found on the PATH!"
    exit 1
fi

# shellcheck disable=2140
cp --recursive "$JOBCONFS_DIR_NAME" "$SEED_WORKSPACE"
chown --recursive "$JENKINS_SYSTEM_USERNAME":"$JENKINS_SYSTEM_USERNAME" "${SEED_WORKSPACE}/${JOBCONFS_DIR_NAME}"

exit 0
