#!/bin/bash
# NOTES: do not rely on jenkins user global git config file
# as future projects (this one included) will truncate the generic credential list.
# What I expect is that cache will allow the program to stash its credentials in memory,
# meaning it will no longer rely on the global config after the first time (assuming the timeout is adequate).

git config --global credential.helper "cache --timeout=30"
git config --global credential.username "$JENKINS_GIT_CREDENTIAL_USERNAME"

. ".env"

. "${PROJECT_SCRIPTS_DIRECTORY}/packerbuilds"
packerbuilds
