#!/bin/bash
# Used by GIT_ASKPASS to non-interactively 
# receive git password from user.
# For reference: https://stackoverflow.com/questions/31218599/supplying-a-password-to-git-in-a-bash-script#answer-55418149
echo "$JENKINS_GIT_CREDENTIAL_PASSWORD"
